"""empty message

Revision ID: ced869262026
Revises: f479add74799
Create Date: 2024-04-06 16:52:05.023557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ced869262026'
down_revision = 'f479add74799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('passkey',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('device_id')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_ibfk_1', 'devices', ['device_id'], ['id'])
        batch_op.drop_column('username')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('passkey',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
